# Generated by Django 2.1.7 on 2019-02-21 12:12

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('app', '0002_auto_20190219_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserB',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User B',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='convidados',
            field=models.ManyToManyField(blank=True, related_name='convidados', to=settings.AUTH_USER_MODEL),
        ),
    ]
