# Generated by Django 2.1.7 on 2019-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190221_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
    ]
